In [1]:
import numpy as np

In [2]:
x = np.arange(11)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [3]:
x = np.zeros((3, 3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [4]:
x = np.random.randint(1, 11, size=(5, 5))
print(x)

[[ 7  9  9 10  1]
 [ 4  4  4  6  8]
 [ 6  5  6 10  5]
 [ 1  7  6 10  8]
 [ 7  2  6  7  8]]


In [5]:
x = np.random.randint(2, size=(4, 4))
print(x)

[[0 1 0 1]
 [1 1 1 1]
 [1 1 0 1]
 [0 1 1 0]]


In [6]:
a = np.random.randint(1, 11, (4))
b = np.random.randint(1, 11, (4))
print(a + b)
print(a * b)
print(a - b)

[14 12 18 13]
[40 20 80 36]
[ 6  8  2 -5]


In [7]:
a = np.random.randint(1, 11, (7))
b = np.random.randint(1, 11, (7))
print(np.dot(a, b))

191


In [8]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 3))
print(np.dot(a, b))

[[54 54 70]
 [64 64 88]]


In [9]:
x = np.random.randint(1, 11, size=(3, 3))
print(np.linalg.inv(x))

[[ -9.    1.5   2.5]
 [-11.    1.5   3.5]
 [  7.   -1.   -2. ]]


In [10]:
a = np.random.randint(2, size=(4, 4))
print(a.T)

[[1 1 1 1]
 [0 0 0 1]
 [1 1 1 0]
 [1 1 0 1]]


In [11]:
a = np.random.randint(1, 11, size=(3, 4))
b = np.random.randint(1, 11, (4))
print(np.dot(a, b))

[124 100  74]


In [12]:
a = np.random.randint(2, size=(2, 3))
b = np.random.randint(2, size=3)
print(np.dot(a, b))

[1 1]


In [13]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(a * b)

[[54  9]
 [72  4]]


In [14]:
a = np.random.randint(1, 11, size=(2, 2))
b = np.random.randint(1, 11, size=(2, 2))
print(np.dot(a, b))

[[32 44]
 [54 65]]


In [15]:
a = np.random.randint(1, 101, size=(5, 5))
print(np.sum(a))

1176


In [16]:
a = np.random.randint(1, 11, size=(4, 4))
b = np.random.randint(1, 11, size=(4, 4))
print(a-b)

[[-8 -3  6  4]
 [ 2  3 -9 -1]
 [ 7  2  3  2]
 [ 3 -3  0  1]]


In [17]:
x = np.random.randint(2, size=(3, 3))
print(x.sum(axis=1))

[1 3 2]


In [18]:
x = np.random.randint(1, 11, size=(3, 4))
print(np.square(x))

[[81  4 25 16]
 [81 16 16 25]
 [ 9  1  1  9]]


In [19]:
x = np.random.randint(1, 51, size=4)
print(np.sqrt(x))

[7.07106781 5.29150262 6.78232998 6.78232998]
